### PR TITLE
sort and argsort operations applied in axis

### LINKED ISSUE #74: argsort and sort
At some level (i.e. this has an `axis` parameter), sort the array. Define the `argsort` version in C++ and we can do the `sort` with an array-slice on the Python side.

Sort orders for numbers in NumpyArray are easy to define, but something will have to be done to sort arrays and records as well. Python has an ordering defined on lists:

```python
>>> [1, 2, 3] < [1, 2]
False
>>> [1, 2, 3] > [1, 2]
True
```

but not records (dicts):

```python
>>> {"one": 1, "two": 2, "three": 3} < {"one": 1, "two": 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

However, our `Record` types are actually tuples—there's a defined field order (unlike Python dicts), so we should be able to inherit a definition from Python tuples:

```python
>>> (1, "a", None) < (1, "a")
False
>>> (1, "a", None) > (1, "a")
True
```

### PR DESCRIPTION
**Pull request by ianna**
Addressing issue #74 
Operations `argsort` and `sort` are applied in `axis` and also takes the following parameters:
```c++
bool ascending
```
If `true`, the values will be sorted in an ascending order.
```c++
bool stable
```
If `true`, the values will be sorted by a stable sort algorithm to maintain the relative order of records with equal keys (i.e. values).
```c++
argsort(int64_t axis, bool ascending, bool stable)
sort(int64_t axis, bool ascending, bool stable)
```

### CODE REVIEW

**Comment by jpivarski** [comment]
Great to see that this has started! I don't think it's necessary, however, to implement all three sorting algorithms unless it's something that comes for free from `#include <algorithm>` or something. We can leave the `axis=0` sorting unimplemented in C++, since it's qualitatively different from the rest and can be implemented at the Python level by deferring to NumPy.

The interesting thing is `sort` and `argsort` of deeply nested lists, `axis=1` and greater. So far, no one has asked for sorting structures, such as

```python
>>> [3, 5, 2] < [4, 1]
True
```

so it would be fine to raise an error if the requested `axis` is not a 1-D NumpyArray, a RawArray, or an IndexedArray that can be evaluated (`carry(index_)`) to a NumpyArray or RawArray. EmptyArrays can also be sorted (trivially). IndexedOptionArrays count as a structure, unless we want to adopt a convention of `None` always being last (or first, but I think last would be better, if handled at all).

Note that Python 3 (unlike Python 2) doesn't like to sort objects of different types, including `None`:

```python
>>> sorted([5, 3, 4])
[3, 4, 5]
>>> sorted([5, 3, 4, None])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'NoneType' and 'int'
>>> sorted([5, 3, 4, []])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'list' and 'int'
```

That's another argument for not handling these cases.

NumpyArrays, RawArrays, EmptyArrays, and evaluated IndexedArrays have something in common: they're all the deepest possible axis, `axis=-1`, which should be the default, once negative axis is handled. (Note to self: I need to implement that right away, so that this PR can be completed!) `axis=-1` is also the default `axis` for `numpy.sort` and `numpy.argsort`, which is great, because then we can make `awkward1.sort`/`awkward1.argsort` a drop-in replacement (in the [NEP18](https://numpy.org/neps/nep-0018-array-function-protocol.html) sense).

NumPy has a definition of sorting with `axis != -1` that is _not_ sorting structures:

```python
>>> numpy.sort([[3.3, 2.2, 4.4], [1.1, 5.5, 3.3]], axis=-1)
array([[2.2, 3.3, 4.4],
       [1.1, 3.3, 5.5]])
>>> numpy.sort([[3.3, 2.2, 4.4], [1.1, 5.5, 3.3]], axis=-2)
array([[1.1, 2.2, 3.3],
       [3.3, 5.5, 4.4]])
```

It's similar to the way that reducers with `axis != -1` is handled:

```
>>> numpy.min([[3.3, 2.2, 4.4], [1.1, 5.5, 3.3]], axis=-1)
array([2.2, 1.1])
>>> numpy.min([[3.3, 2.2, 4.4], [1.1, 5.5, 3.3]], axis=-2)
array([1.1, 2.2, 3.3])
```

Having gone through that exercise:

```python
>>> import awkward1 as ak
>>> ak.min([[3.3, 2.2, 4.4], [1.1, 5.5]], axis=-1)
<Array [2.2, 1.1] type='2 * ?float64'>
>>> ak.min([[3.3, 2.2, 4.4], [1.1, 5.5]], axis=-2)
<Array [1.1, 2.2, 4.4] type='3 * ?float64'>
```

I can say that it's really complicated: you have to pass down and update a `nextcarry`, `nextparents`, and `nextstarts` at every list level.

**So don't implement sorting for axis != -1 right now. But do set up the infrastructure so that it would be possible in the future.**

That is, follow the structure of `reduce_next`:

https://github.com/scikit-hep/awkward-1.0/blob/bf44d0244d6eec460c00837afea09a42761f1d45/src/libawkward/array/ListOffsetArray.cpp#L984-L1104

but don't fill in all the cases. This kind of operation, for which `axis=-1` is the natural default (like reducers and unlike most others, such as `rpad` or `fillna`) does not use `axis_wrap_if_negative` (so I'm off the hook for implementing that). Instead, it has a common entry function, like `Content::reduce`:

https://github.com/scikit-hep/awkward-1.0/blob/bf44d0244d6eec460c00837afea09a42761f1d45/src/libawkward/Content.cpp#L79-L113

that passes down `negaxis` instead of `axis`. (For these types of operations, it's more natural to think in terms of the negative axis, so when the user supplies `-1`, we call that `1`.) The `parents` is an array of integers with the same length as the current level that indicates which outer list each element belongs to. For instance,

```python
[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]
```

means that the 15 elements at this level are nested inside of

```python
[[. . . . .] [. . . . .] [. . . . .]]
```

So `parents` is like bottom-up pointers containing the same information as the top-down `starts` pointers. For the same array, `starts` is

```python
[0, 5, 10]
```

For most reducers, I only needed `parents`, but last night I added `argmin` and `argmax`, which needed `starts` so that the `arg` integers could be relative to the start of the current list, rather than being absolute numbers. (Since you're doing `argsort`, you'll need it, too.) The two of these have all the information that would be needed for handling any `axis`; the `parents` are only monotonically increasing for `axis=-1`.

Just to reiterate, you do not need to implement `axis != -1`, but create and use the `parents` and `starts` similar to the `reduce` and `reduce_next` methods, even though they're overkill for this case. There are huge blocks of `reduce_next` that do not need a parallel yet—for example,

```c++
if (!branchdepth.first  &&  negaxis == branchdepth.second)
```

is only for `axis != -1`, and this is more than half of the function. The `else` clause,

https://github.com/scikit-hep/awkward-1.0/blob/bf44d0244d6eec460c00837afea09a42761f1d45/src/libawkward/array/ListOffsetArray.cpp#L1071-L1103

doesn't have a `nextcarry` because the relevant contents are contiguous (it has a `getitem_range_nowrap` instead), the `nextparents` are relatively simple, and the `nextstarts` are simply `util::make_starts(offsets_)`.

You can have ListArray and RegularArray just call `toListOffsetArray64()` and handle all the list stuff in `ListOffsetArrayOf<T>::sort_next`. Don't handle option types yet (IndexedOptionArray, ByteMaskedArray, BitMaskedArray) because I'll be correcting the definition by solving issue #166; it's currently not correct. UnionArrays and RecordArrays are relatively simple; see the `reduce_next` examples.

**Comment by jpivarski** [comment]
All the commits I just made were for setting up documentation sites. That's been settled: Doxygen will go to awkward-array.readthedocs.org (under [static_](https://awkward-array.readthedocs.io/en/latest/_static/), which can't be changed for technical reasons related to Sphinx) and the tutorials go to GitHub Pages ([here](https://scikit-hep.org/awkward-1.0/index.html)). Merging that shouldn't affect your work.

However, I'm about to make a big change, source-file-wise, by enforcing an 80-character limit everywhere. I just checked over the changes here and it looks like you only have stubs: that should still be easy to merge. But if you have more substantial changes in your local git repo, then it could be difficult. I'll start working on that 80-character limit in another PR and not merge it until I hear back from you about whether that would present any difficulties.

So let me know; thanks!

**Comment by ianna** [comment]
> All the commits I just made were for setting up documentation sites. That's been settled: Doxygen will go to awkward-array.readthedocs.org (under [static_](https://awkward-array.readthedocs.io/en/latest/_static/), which can't be changed for technical reasons related to Sphinx) and the tutorials go to GitHub Pages ([here](https://scikit-hep.org/awkward-1.0/index.html)). Merging that shouldn't affect your work.
> 
> However, I'm about to make a big change, source-file-wise, by enforcing an 80-character limit everywhere. I just checked over the changes here and it looks like you only have stubs: that should still be easy to merge. But if you have more substantial changes in your local git repo, then it could be difficult. I'll start working on that 80-character limit in another PR and not merge it until I hear back from you about whether that would present any difficulties.
> 
> So let me know; thanks!

Thanks for letting me know! No worries, I'm ok with merging conflicts. This PR will be easy to merge - all these are new member functions. Git merge usually messes a bit `cpu-kernels`. To avoid this I'll place the new functions at the end when I merge master to my branch.

**Comment by jpivarski** [comment]
Let's use this "convert to draft" GitHub feature instead of the "`[WIP]`" naming convention. The WIP-bot counts as an unfinished test, so all the passing commits are yellow dots, not clearly indicating which ones actually passed all the real tests—I've never really liked it, for that reason, and now "convert to draft" looks like an acceptable alternative. The draft feature also provides more protection against accidentally clicking the "merge" button.

That will be in the CONTRIBUTING.md that's still in my head.

I've seen your commits. Do you feel like you're making progress, or is there some issue you want to talk about? If so, we can arrange a time.

**Comment by ianna** [comment]
> Let's use this "convert to draft" GitHub feature instead of the "`[WIP]`" naming convention. The WIP-bot counts as an unfinished test, so all the passing commits are yellow dots, not clearly indicating which ones actually passed all the real tests—I've never really liked it, for that reason, and now "convert to draft" looks like an acceptable alternative. The draft feature also provides more protection against accidentally clicking the "merge" button.
> 
> That will be in the CONTRIBUTING.md that's still in my head.
> 
> I've seen your commits. Do you feel like you're making progress, or is there some issue you want to talk about? If so, we can arrange a time.

Hi Jim,
I think, I'm making progress. I'm debugging the sorting ranges definition based on relative indices for multi dimensional arrays. It is fun :-)
I did not know that making an existing PR to a draft PR feature has been implemented. Let's use it!

**Comment by ianna** [comment]
@jpivarski - I don't have Windows accessible to test the build - is it expected that it fails?

```
    Generating Code...
  Not able to access compiler path (on Windows), using CMake default
  Traceback (most recent call last):
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\setuptools\build_meta.py", line 212, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\setuptools\build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 137, in <module>
      setup(name = "awkward1",
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-u5s2z4k6\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 87, in run
      _build_ext.run(self)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 42, in build_extensions
      self.build_extension(x)
    File "setup.py", line 84, in build_extension
      subprocess.check_call(["cmake", "--build", build_dir] + build_args)
    File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', 'build\\temp.win-amd64-3.8\\Release', '--config', 'Release', '--', '/m', '/m']' returned non-zero exit status 1.
  Building wheel for awkward1 (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for awkward1
Failed to build awkward1
Cleaning up...
```

**Comment by jpivarski** [comment]
Builds on Windows should work.

I looked at the full log and found that the first error is this:

```
2020-04-20T14:13:47.6069252Z   C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-854ndqim\src\libawkward\array\NumpyArray.cpp(2355): error C2146: syntax error: missing ')' before identifier 'or' [C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-854ndqim\build\temp.win-amd64-3.8\Release\awkward-objects.vcxproj]
```

I don't immediately see the error when I look at this line in your branch, but it happens in the middle of the argsort function:

https://github.com/scikit-hep/awkward-1.0/blob/51b0be556633954bdd12c077aed1c03357f23703/src/libawkward/array/NumpyArray.cpp#L2314-L2481

and there are `#ifdef _MSC_VER` switches in there that could, in principle, cause a syntax error on Windows that doesn't show up on other systems.

**Comment by ianna** [comment]
> Builds on Windows should work.
> 
> I looked at the full log and found that the first error is this:
> 
> ```
> 2020-04-20T14:13:47.6069252Z   C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-854ndqim\src\libawkward\array\NumpyArray.cpp(2355): error C2146: syntax error: missing ')' before identifier 'or' [C:\Users\VssAdministrator\AppData\Local\Temp\pip-req-build-854ndqim\build\temp.win-amd64-3.8\Release\awkward-objects.vcxproj]
> ```
> 
> I don't immediately see the error when I look at this line in your branch, but it happens in the middle of the argsort function:
> 
> https://github.com/scikit-hep/awkward-1.0/blob/51b0be556633954bdd12c077aed1c03357f23703/src/libawkward/array/NumpyArray.cpp#L2314-L2481
> 
> and there are `#ifdef _MSC_VER` switches in there that could, in principle, cause a syntax error on Windows that doesn't show up on other systems.

I'll try to find a PC :-)

**Comment by jpivarski** [comment]
Incidentally, these "Windows ifdefs" can also be tested with a 32-bit version of Linux. For faster debugging on systems with these alternative `format_` definitions, I use one of these Docker images (I can't remember which):

```
% docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
i386/ubuntu                         latest              f015d121c3ab        3 months ago        64.8MB
nickcis/fedora-32                   latest              5cf360091dd7        4 years ago         212MB
32bit/debian                        latest              ec51524b3826        5 years ago         272MB
```

It seems that I used `i386/ubuntu` most recently. Looking in my command history, I mounted a directory on my host computer (for persistence) while running the 32-bit Docker image and installed a 32-bit version of Miniconda through the Docker image into the persistent directory. It complained that my host is 64 bit, but that's because Docker images _do_ leak information about the host, and I could safely disregard this warning. I installed CMake, GCC, and NumPy using Conda to ensure that I got 32-bit versions of all of them, and git cloned awkward1 into the persistent volume.

With all that set up, the compiler goes into the `#ifdefs` that are triggered by Windows OR 32-bit, and had faster turn-around time on debugging them.

For anything that actually depends on Windows, as opposed to these 32-bit `format` definitions, I don't have a good workflow. I've never been able to run Windows in a virtual machine with compilers. When something truly Windows-related fails, Azure is the only way I have to debug it, too.

**Comment by jpivarski** [comment]
> I'll try to find a PC :-)

Finding a PC with properly set-up compilers is the hard part. Microsoft makes Windows virtual machines available, but the purpose is to test web pages on their Edge web browser, not compiling C++ programs. I haven't found a virtual machine with Visual Studio and all that. If you're looking for laptops, particularly a laptop owned by somebody who actually does C++ work, you may have more success.

**Comment by ianna** [comment]
> > I'll try to find a PC :-)
> 
> Finding a PC with properly set-up compilers is the hard part. Microsoft makes Windows virtual machines available, but the purpose is to test web pages on their Edge web browser, not compiling C++ programs. I haven't found a virtual machine with Visual Studio and all that. If you're looking for laptops, particularly a laptop owned by somebody who actually does C++ work, you may have more success.

Well... it turns out the Windows compiler does not define alternative tokens for logical operators.

BTW, thanks a lot for cleaning the MacOS warnings! I've updated to master and **all** the warnings are gone.

**Comment by jpivarski** [comment]
> BTW, thanks a lot for cleaning the MacOS warnings! I've updated to master and all the warnings are gone.

(Thank @veprbl!)

**Comment by ianna** [comment]
@jpivarski - I think, I'm nearly done with this PR. There are a few irregularities I'd need to fix (see the comments in the test), but I would like to discuss it beforehand. Would you have time tomorrow? Thanks

**Comment by jpivarski** [comment]
> @jpivarski - I think, I'm nearly done with this PR. There are a few irregularities I'd need to fix (see the comments in the test), but I would like to discuss it beforehand. Would you have time tomorrow? Thanks

Sure: 11am Chicago == 18:00 Geneva on Skype?

**Comment by ianna** [comment]
@jpivarski - please, ignore the `recurse` method for the time being. I need it to test the arrays shape consistency. Since the logic hasn't been reviewed yet, I decided to keep it for now. I'll remove it when the review comments are addressed. Thanks!

**Comment by jpivarski** [comment]
I intend to review this, but first I rebooted the Windows tests, as they all timed out at 1 hour. If it's not some transient problem with Azure (i.e. if it happens again), then it's likely a pointer bug that gets missed by the other two platforms. That's happened to me before, and by debugging it on Windows, I found a hidden pointer bug. I just wish we had a better way to run Windows than compiling the whole project every time in Azure.

**Comment by ianna** [comment]
@jpivarski - All tests pass! I've finished with the code cleanup. I'll wait for you to review it. Thanks!

**Comment by jpivarski** [comment]
Great! I'll review it, possibly tomorrow. Thanks!

File: src/libawkward/array/EmptyArray.cpp [hunk 1]
```diff
@@ -450,6 +450,46 @@ namespace awkward {
...
+    std::cout << "argsort an EmptyArray:\n" <<
+      asnumpy.get()->tostring() << "\n";
+     ContentPtr out = asnumpy.get()->argsort_next(negaxis,
+                                       starts,
+                                       parents,
+                                       outlength,
+                                       ascending,
+                                       stable,
+                                       keepdims);
+    std::cout << out.get()->tostring() << "\n";
```
Comment (jpivarski) [inline src/libawkward/array/EmptyArray.cpp]: Debugging code (`std::cout`) should be removed.

File: src/cpu-kernels/operations.cpp [hunk 2]
```diff
@@ -3654,3 +3654,253 @@ ERROR awkward_bitmaskedarray_to_indexedoptionarray_64(
...
+    toptr,
+    fromindex,
+    length);
+}
+
+template <typename T>
+ERROR awkward_sort(
+  T* toptr,
+  const T* fromptr,
+  const size_t* fromindex,
```
Comment (jpivarski) [inline src/cpu-kernels/operations.cpp]: The interface between the kernels and the main codebase should be machine-independent, so a specific type, most likely `int64_t*`, should be used here. (I know that means upstream changes to ensure that all the values in the array are 64-bit, but that's the point—to only send machine-independent values over the interface.)

Also, unless you explicitly know that `fromindex[0]` is the first value, this argument should probably be accompanied by a `fromindexoffset`, like `parents` and `parentsoffset` below. In some cases, it might be impossible for values like `parentsoffset` to _not_ be zero, due to how it's built, but I've always erred on the side of caution. The "to" arrays, such as `toptr` here, can be known to have zero offset because they were created immediately before being passed into the kernel function.

The same might be the case for `fromptr`. It was created by reducer kernels, right? If so, the equivalent user of `fromptr` in the reducer code might tell you if a `fromptroffset` is needed or not.

File: tests/test_0074-argsort-and-sort.py [hunk 3]
```diff
@@ -0,0 +1,419 @@
...
+    assert awkward1.to_list(array.argsort(0, True, False)) == [
+       [[1, 1, 1, 1, 1],
+        [1, 1, 1, 1, 1],
+        [1, 1, 1, 1, 1]],
+
+       [[0, 0, 0, 0, 0],
+        [0, 0, 0, 0, 0],
+        [0, 0, 0, 0, 0]]]
+
+def test_RecordArray():
```
Comment (jpivarski) [inline tests/test_0074-argsort-and-sort.py:346]: These are good tests of variable-length lists, but none of them actually test what happens when a "sort" request hits a RecordArray. Until an `order` argument is added (as in [numpy.sort](https://numpy.org/devdocs/reference/generated/numpy.sort.html)), RecordArrays don't have much effect on sorting, but it shouldn't break.

Similarly, a UnionArray of compatible types (integers and floats, for instance) should sort appropriately. I saw in your implementation of `UnionArrayOf<T, I>::sort_next` that it's set up to do the right thing: try simplifying the array, and if that works, sort the simplified (i.e. non-UnionArray) array. Although these are trivial cases, there should be a test for each, showing that they do the trivial thing.

File: include/awkward/array/RawArray.h [hunk 4]
```diff
@@ -63,7 +66,7 @@ namespace awkward {
 
     const std::string
       purelist_parameter(const std::string& key) const override {
-      parameter(key);
+      return parameter(key);
```
Comment (jpivarski) [inline include/awkward/array/RawArray.h:70]: Good catch! Thanks!

File: include/awkward/array/RawArray.h [hunk 5]
```diff
@@ -117,7 +120,7 @@ namespace awkward {
     bool
       equal(const FormPtr& other,
             bool check_identities,
-            bool check_parameters) const {
+            bool check_parameters) const override {
```
Comment (jpivarski) [inline include/awkward/array/RawArray.h]: Thanks! (You can close these two inline comments immediately.)

File: include/awkward/array/RawArray.h [hunk 6]
```diff
@@ -920,6 +923,110 @@ namespace awkward {
...
+      }
+      struct Error err = util::awkward_numpyarray_sort<T>(
+        ptr.get(),
+        ptr_.get(),
+        &result[0],
+        starts.ptr().get(),
+        parents.ptr().get(),
+        parents.offset(),
+        length_);
+      util::handle_error(err, classname(), nullptr);
```
Comment (jpivarski) [inline include/awkward/array/RawArray.h]: **HERE**

I see that the `result` is the container where the sorting happens; this should be an `Index64` if it must be an argsort-style index, and then you can use it in `carry` to apply that index to the `ptr`.

File: include/awkward/array/RawArray.h [hunk 7]
```diff
@@ -920,6 +923,110 @@ namespace awkward {
...
+          [&](size_t i1, size_t i2) {return getitem_at_nowrap(i1) < getitem_at_nowrap(i2);});
+      }
+      else if(!ascending  &&  stable) {
+        std::stable_sort(result.begin(), result.end(),
+          [&](size_t i1, size_t i2) {return getitem_at_nowrap(i1) > getitem_at_nowrap(i2);});
+      }
+      struct Error err = awkward_argsort_64(
+        ptr.get(),
+        &result[0],
+        length_);
```
Comment (jpivarski) [inline include/awkward/array/RawArray.h]: **HERE** (same as above)

File: src/libawkward/array/IndexedArray.cpp [hunk 8]
```diff
@@ -1980,6 +1980,216 @@ namespace awkward {
...
+      int64_t start = starts.getitem_at_nowrap(parent);
+      int64_t nextparent = nextparents.getitem_at_nowrap(j);
+      if (parent == nextparent) {
+        nextoutindex.setitem_at_nowrap(i, j);
+        ++j;
+      }
+      else {
+        nextoutindex.setitem_at_nowrap(i, -1);
+      }
+    }
```
Comment (jpivarski) [inline src/libawkward/array/IndexedArray.cpp]: **HERE**

This is iterating over `parents`, which is _O(n)_ in array length. What's written here is almost exactly a kernel anyway, just replacing the `getitem_at_nowrap` and `setitem_at_nowrap` with direct array access. That way, if the data are on a GPU, they won't be pulled off one at a time (I think kernel launch overhead is 10 μs); a variant of the above would run completely on the GPU, dispatched from a single function call here.

File: src/libawkward/array/IndexedArray.cpp [hunk 9]
```diff
@@ -1980,6 +1980,216 @@ namespace awkward {
...
+        out = raw->toListOffsetArray64(true);
+      }
+      if (ListOffsetArray64* raw =
+        dynamic_cast<ListOffsetArray64*>(out.get())) {
+        Index64 outoffsets(starts.length() + 1);
+        if (starts.length() > 0  &&  starts.getitem_at_nowrap(0) != 0) {
+          throw std::runtime_error(
+            "sort_next with unbranching depth > negaxis expects a "
+            "ListOffsetArray64 whose offsets start at zero");
+        }
```
Comment (jpivarski) [inline src/libawkward/array/IndexedArray.cpp:2061]: This use of `getitem_at_nowrap` is allowed because it only gets one value (the first). If the data were on a GPU, a kernel would be launched to get that individual value, but 10 μs is not a huge overhead to add at the beginning of "sort this whole array for me."

File: include/awkward/Content.h [hunk 10]
```diff
@@ -675,6 +675,43 @@ namespace awkward {
...
+    /// stable sort algorithm to maintain the relative order of records with
+    /// equal keys (i.e. values).
+    virtual const ContentPtr
+      sort_next(int64_t negaxis,
+                const Index64& starts,
+                const Index64& parents,
+                int64_t outlength,
+                bool ascending,
+                bool stable,
+                bool keepdims) const = 0;
```
Comment (jpivarski) [inline include/awkward/Content.h:714]: `keepdims` only makes sense for reducing, not for sorting. It places the result of a summation, for example, inside of a dimension of length 1 instead of removing a dimension, as reducers normally do. (That makes it easier to use reduced arrays in the same expressions with non-reduced arrays; in particular, it allows for broadcasting.)

Sorting maintains the number of dimensions and even the lengths of each dimension, so `keepdims` can't be doing anything. If it's just being passed down the recursion, you can remove it.

File: src/libawkward/array/IndexedArray.cpp [hunk 11]
```diff
@@ -1980,6 +1980,216 @@ namespace awkward {
...
+      int64_t start = starts.getitem_at_nowrap(parent);
+      int64_t nextparent = nextparents.getitem_at_nowrap(j);
+      if (parent == nextparent) {
+        nextoutindex.setitem_at_nowrap(i, j);
+        ++j;
+      }
+      else {
+        nextoutindex.setitem_at_nowrap(i, -1);
+      }
+    }
```
Comment (jpivarski) [inline src/libawkward/array/IndexedArray.cpp]: **HERE**

File: src/libawkward/array/ListOffsetArray.cpp [hunk 12]
```diff
@@ -1680,6 +1682,317 @@ namespace awkward {
...
+      std::sort(result.begin(), result.end(),
+        [&nextcarry](int64_t i1, int64_t i2) {return nextcarry.getitem_at(i1) < nextcarry.getitem_at(i2);});
+
+      Index64 outcarry(nextlen);
+      struct Error err5 =
+        awkward_listoffsetarray_local_preparenext_64(
+        outcarry.ptr().get(),
+        &result[0],
+        nextlen);
+      util::handle_error(err5, classname(), identities_.get());
```
Comment (jpivarski) [inline src/libawkward/array/ListOffsetArray.cpp]: **HERE**

File: src/libawkward/array/ListOffsetArray.cpp [hunk 13]
```diff
@@ -1680,6 +1682,317 @@ namespace awkward {
...
```
Comment (jpivarski) [inline src/libawkward/array/ListOffsetArray.cpp]: **HERE**

File: src/libawkward/array/NumpyArray.cpp [hunk 14]
```diff
@@ -3619,4 +3982,143 @@ namespace awkward {
...
+      }
+      std::transform(start, stop, start,
+                 [&](size_t j) -> size_t { return j - (size_t)offsets[i]; });
+    }
+
+    struct Error err2 = awkward_argsort_64(
+      ptr.get(),
+      &result[0],
+      length);
+    util::handle_error(err2, classname(), nullptr);
```
Comment (jpivarski) [inline src/libawkward/array/NumpyArray.cpp]: **HERE**

File: src/libawkward/array/NumpyArray.cpp [hunk 15]
```diff
@@ -3619,4 +3982,143 @@ namespace awkward {
...
+
+    struct Error err2 = util::awkward_numpyarray_sort<T>(
+      ptr.get(),
+      data,
+      &result[0],
+      starts.ptr().get(),
+      parents.ptr().get(),
+      parents.offset(),
+      parents.length());
+    util::handle_error(err2, classname(), nullptr);
```
Comment (jpivarski) [inline src/libawkward/array/NumpyArray.cpp]: **HERE**

File: src/libawkward/array/NumpyArray.cpp [hunk 16]
```diff
@@ -3619,4 +3982,143 @@ namespace awkward {
...
+                             int64_t outlength) const {
+    std::vector<int64_t> result;
+    std::vector<int64_t> ranges(parents.length() + 1);
+    struct Error err = awkward_argsort_prepare_ranges(
+      &ranges[0],
+      parents.ptr().get(),
+      parents.offset(),
+      parents.length(),
+      outlength);
+    util::handle_error(err, classname(), nullptr);
```
Comment (jpivarski) [inline src/libawkward/array/NumpyArray.cpp]: This is going to a kernel, and that's fine, but the interface should be an `Index64` instead of a `std::vector<int64_t>::data`, which would make more sense once the actual sorting goes onto the kernel side.

File: src/libawkward/array/NumpyArray.cpp [hunk 17]
```diff
@@ -3619,4 +3982,143 @@ namespace awkward {
...
+
+    for (auto const& it : ranges) {
+      auto res = std::find(std::begin(ranges), std::end(ranges), it);
+      if (res != std::end(ranges)) {
+        if (result.empty() || result.back() != std::distance(std::begin(ranges), res)) {
+          result.emplace_back(std::distance(std::begin(ranges), res));
+        }
+      }
+    }
```
Comment (jpivarski) [inline src/libawkward/array/NumpyArray.cpp]: **HERE**

The size of these `ranges` scales with the length of the array. This one looks pretty easy to hide in a kernel interface.

**Review by jpivarski — CHANGES_REQUESTED** [review]
Sorry it took me so long to give this a proper review!

What you've done looks great. Looking through the examples in the tests, I see that it does all the right things for two and even three axes, as well as missing values. (Just as in a `numpy.ma.MaskedArray`, the missing values go last. You have them going last regardless of whether the sort is ascending or descending, which is a little odd, but since NumPy doesn't have an `ascending (bool)` parameter in [numpy.sort](https://numpy.org/devdocs/reference/generated/numpy.sort.html), they don't provide guidance. A user can always sort `axis=2` (for instance) and then slice with `:, :, ::-1` to reverse the order of what has been sorted, so always putting the missing values last effectively gives users the choice of whether they want it first or last.)

There is one issue, and it's a blocker: the actual sorting is happening on the C++ side, instead of in the kernels where it belongs. This separation is one of the properties that has to be maintained between the C++ codebase and the kernels: the C++ codebase isn't even allowed to dereference the buffers pointed to by members named `ptr_` (in NumpyArray, RawArray, Index, and Identities). This is the last paragraph in the [Performance considerations section of CONTRIBUTING.md](https://github.com/scikit-hep/awkward-1.0/blob/master/CONTRIBUTING.md#performance-considerations), although the reference there is pretty brief—I probably ran out of time or energy writing that up.

The "slow control" mentioned in the CONTRIBUTING.md is referring to the C++ codebase, with "fast math" being the kernels. To be specific about slow and fast, any algorithm whose big-O time is not constant with respect to the number of elements in an array has to be in the kernels. This is why we can justify using "slow" virtual methods on accessors like `getitem_at` or `getitem_at_nowrap`: they must never be used in a loop over all entries of an array buffer. The kernels directly access them as C-style arrays with no virtual method overhead.

But there's a functionality, as opposed to just performance, reason why the separation must be maintained: Reik and Anish have [started developing libawkward-gpu-kernels.so](https://github.com/scikit-hep/awkward-1.0/projects/1), which means that some of the pointers referenced by the `ptr` member data will actually reside on GPUs. Dereferencing them or calling any C++ function like `std::sort` that dereferences them will cause segmentation faults.

You've passed lambda functions to `std::sort` and those lambda functions access elements via `getitem_at` and `getitem_at_nowrap`, which will protect us from segmentation faults because these methods invoke kernels that dispatch to [kernels that get one value from the buffer](https://github.com/scikit-hep/awkward-1.0/blob/522253297cfbe3bc27ad989a65fab7e0d5f7b960/src/cpu-kernels/getitem.cpp#L2812-L2877), and there will be both CPU and GPU versions of those kernels. However, the safety would come at a terrible performance price: the sorting functions would launch one GPU kernel per value to take data off the GPU one at a time.

Your implementation can be used, it just has to be put behind the kernels interface. That is, `std::sort` would be invoked inside of libawkward-cpu-kernels.so, though it interfaces with the C++ codebase through plain arrays. (Only the interface of the kernels needs to be pure C. The implementations are as simple as possible to aid compiler optimizations, but as you can see from the templates that are there, the internal implementations can use C++.) Anish and Reik would then have to find GPU equivalents of the C++ standard library's sorting algorithms, but they probably exist in some library. (Or we'll say that sorting is one of the operations that can only be done on the CPU, though having too many of those would slow down analysis workflows by requiring arrays to be moved to and from the GPU to perform operations not available on one of the two platforms.)

Inline, I've labeled everything that has to be moved into cpu-kernels with "HERE". Just like reducers.h/reducers.cpp, you should create a sorting.h/sorting.cpp in cpu-kernels. Right now, Reik is developing automated scans of the kernels with a modified C99-to-AST parser to document what we have and prepare most of it for automated conversion to CUDA. (75% of the kernels are embarrassingly parallel, so automated translation will be possible for most of them.) The sorting kernels need to be separated out because his parser won't be able to deal with all of the C++. (He's modifying it to do C99 + templates; involving a full C++ parser like LLVM would be a much larger project.) Once separated, we can leave the sorting kernels to be translated by hand.

I've labeled everything that has to move to sorting.h/sorting.cpp in cpu-kernels with "HERE".

File: src/libawkward/array/EmptyArray.cpp (hunk 1 above)
Comment (ianna) [reply src/libawkward/array/EmptyArray.cpp]: done, sorry about that, it meant to be removed :-)

File: src/libawkward/array/NumpyArray.cpp (hunk 16 above)
Comment (ianna) [reply src/libawkward/array/NumpyArray.cpp]: done

File: src/libawkward/array/NumpyArray.cpp (hunk 15 above)
Comment (ianna) [reply src/libawkward/array/NumpyArray.cpp]: I've moved all this code to cpu-kernels.

File: src/libawkward/array/NumpyArray.cpp (hunk 14 above)
Comment (ianna) [reply src/libawkward/array/NumpyArray.cpp]: done

File: src/cpu-kernels/operations.cpp (hunk 2 above)
Comment (ianna) [reply src/cpu-kernels/operations.cpp]: done

File: include/awkward/array/RawArray.h (hunk 6 above)
Comment (ianna) [reply include/awkward/array/RawArray.h]: done

File: include/awkward/array/RawArray.h (hunk 7 above)
Comment (ianna) [reply include/awkward/array/RawArray.h]: done

File: src/libawkward/array/IndexedArray.cpp (hunk 8 above)
Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp]: done

File: src/libawkward/array/IndexedArray.cpp (hunk 9 above)
Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp:2061]: agree, thanks!

File: src/libawkward/array/IndexedArray.cpp (hunk 11 above)
Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp]: done

File: src/libawkward/array/ListOffsetArray.cpp (hunk 12 above)
Comment (ianna) [reply src/libawkward/array/ListOffsetArray.cpp]: done

File: src/libawkward/array/NumpyArray.cpp (hunk 17 above)
Comment (ianna) [reply src/libawkward/array/NumpyArray.cpp]: done

File: src/libawkward/array/ListOffsetArray.cpp (hunk 13 above)
Comment (ianna) [reply src/libawkward/array/ListOffsetArray.cpp]: done

File: include/awkward/Content.h (hunk 10 above)
Comment (ianna) [reply include/awkward/Content.h:714]: `keepdims` is used in the `ListOffsetArray` to sort the content and keep its shape. I'll see if there is a simpler way of doing it.

File: tests/test_0074-argsort-and-sort.py (hunk 3 above)
Comment (ianna) [reply tests/test_0074-argsort-and-sort.py:346]: I realised that I need to fix the `string` sorting as they are sorted internally as `char`s...

**Comment by ianna** [comment]
@jpivarski - please, let me know if I need to change the `sorting.cpp`. Thanks.

File: include/awkward/Content.h (hunk 10 above)
Comment (jpivarski) [reply include/awkward/Content.h:714]: At the entry point for `sort_next` and `argsort_next`, the value of `keepdims` is always `true`. It doesn't need to be an argument.

**Review by jpivarski — APPROVED** [review]

**Comment by jpivarski** [comment]
I'm going to check this over and make any small changes to finish it up. (For instance, a `git merge master` was needed to fix linker errors on Linux.) Thanks for taking it this far! It represents an enormous amount of work.
