### PR TITLE
Fixes #162. Replaces all Raw Pointer Access with wrappers.

### LINKED ISSUE #162: Layer 3 C++ code must never directly access Index.ptr, NumpyArray.ptr, or RawArray.ptr contents
Right now, there seem to be no exceptions to the rule that layer 3 (i.e. libawkward.so, as opposed to libawkward-cpu-kernels.so) code never _iterates_ over the raw buffers, but there are a few isolated cases where it accesses the first or last element. These have to be turned into kernels (albeit trivial ones) because when the buffers are hosted on a GPU, any direct access would cause a segmentation fault.

This can be done in a visual inspection sweep over the code—it wouldn't take longer than an afternoon. Suspicious cases look like

```c++
offsets_.get().ptr()[0]      // (first)
```

or

```c++
offsets_.get().ptr()[offsets_.length() - 1]      // (last)
```

Some are assignments:

```c++
offsets_.get().ptr()[0] = 0;
```

They should all be centralized in `Index` methods, like `Index::getitem_at_nowrap` and those methods should call the kernels.

### PR DESCRIPTION
**Pull request by trickarcher**
For now, the raw ptr access is replaced by their respective methods. Although, in `RawArray.h` there's a method `merge` which attempts to make a temporary `RawArray` named `raw_other` and memcpy into `ptr`, the problem is when replacing the raw_ptr access with `IndexOf<T>::getitem_at_nowrap`, the compiler does give out a `-fpermissive` warning which is due to the access of temporary memory. I'll keep looking for a better fix for this.

### CODE REVIEW

**Comment by trickarcher** [comment]
The new commit, creates two methods in the `cpu-kernels` to `get` and `set` contents. However, in doing this I was forced to break the `extern "C"` interface which is against the current design.

File: src/cpu-kernels/getitem.cpp [hunk 1]
```diff
@@ -1082,3 +1082,25 @@ ERROR awkward_listarrayU32_getitem_jagged_descend_64(int64_t* tooffsets, const i
...
+
+template<typename T>
+EXPORT_SYMBOL T getitem_at_nowrap_cpu(const std::shared_ptr<T> ptr_, size_t at) {
+  return ptr_.get()[at];
+}
+
+template<typename T>
+EXPORT_SYMBOL void setitem_at_nowrap_cpu(const std::shared_ptr<T> ptr_, size_t at, T value) {
+  ptr_.get()[at] = value;
+}
```
Comment (jpivarski) [inline src/cpu-kernels/getitem.cpp]: You're right that this breaks design, but it can also be avoided by just

```c++
template <typename T>
EXPORT_SYMBOL T awkward_index_getitem_at_nowrap(const T* ptr, int64_t offset, int64_t at) {
  return ptr[(size_t)(offset + at)];
}

template <typename T>
EXPORT_SYMBOL void awkward_index_setitem_at_nowrap(T* ptr, int64_t offset, int64_t at, T value) {
  ptr[(size_t)(offset + at)] = value;
}
```

and used (in Index.cpp) as

```c++
template <typename T>
T IndexOf<T>::getitem_at_nowrap(int64_t at) {
  return awkward_index_getitem_at_nowrap(ptr_.get(), offset_, at);
}

template <typename T>
void IndexOf<T>::setitem_at_nowrap(int64_t at, T value) {
  awkward_index_setitem_at_nowrap(ptr_.get(), offset_, at, value);
}
```

Now the only type that gets passed over the border is a raw pointer, which is fully compatible with the extern C interface. That's what all the other kernel functions do. Most C++ style guides discourage this because the raw pointer doesn't track ownership—if the layer 3 code (libawkward) deletes a buffer before the layer 4 code (cpu-kernels) is done with it, there would be data corruption or a segmentation fault. So the rule that we shouldn't do that is explicit in the design: layer 3 code should ensure the existence of buffers while layer 4 code runs. Since we don't do any multithreading in Awkward Array (that's up to code that _uses_ Awkward Array), this is easy: when a layer 3 function calls a layer 4 function, its thread waits until the layer 4 function is done, so the lifetimes of these buffers are guaranteed.

Some conventions:

   * The names of all kernel functions start with "awkward_" and usually include the class they're closely associated with, such as "awkward_index_" here. All the template instantiations (for `Index8`, `IndexU8`, ..., `Index64`) can then be named `awkward_index8_getitem_at_nowrap`, etc. Unmangled names have no C++ namespaces, so we use "awkward_" as a prefix to avoid collisions (a common practice in C).
   * The function shouldn't be designated "_cpu" because all the GPU functions will be in a separate library. Maybe they'll all have to have distinct names because they live in the same namespace—I haven't figured out how that's going to work yet—but those names will be defined systematically. (Maybe we'll rename all the "awkward_" to "awkward_cpu_", but we'll come to that later.)
   * Also a naming convention: trailing underscores (e.g. `ptr_` vs `ptr`) are for class member data. Once a variable is in a kernel function, there are no classes and therefore no class member data.
   * All integer types in the interface have fully specified bit widths. Even though `at` will be used as an array position, `size_t`, it's passed as an `int64_t` and is cast inside the kernel function. C's architecture-dependent integer widths are horrible, so we rein in the madness by making `int64_t` the basic integer type, delving into the others only when necessary. In CI, the Windows 32-bit build (where `size_t` is 32-bit, rather than 64-bit) catches and warns us about implicit integer type conversions, so we make all the integer type conversions explicit. Yes, we're not protected against integer overflows, but at least we know where the overflows can happen because there's an explicit conversion in the code. The unsigned integer types are the worst: reasonable-looking subtractions and checks for `i >= 0` can behave unexpectedly if the integer `i` is declared as unsigned, as is the case with `size_t`. After encountering several bugs related to this (infinite loops and crashes), I've developed a policy of converting to `size_t` as late as possible.
   * The `offset` accounts for the fact that `ptr` refers to the base pointer of each buffer, but a particular Index might be a view into a subset of that buffer that doesn't start at zero. For example, perhaps the user sliced an array with a slice that doesn't start at zero: `array[10:15]`. The slice (`array[10:15]`) shares data with the original array (`array`) to avoid an unnecessary copy. However, both objects have to increment the same reference counter, so their `ptr_` shared pointers point at the same base address (`&array[0]`). They are distinguished by having a different offset (where it begins) and length (how far it goes; equivalently, we could have stored `start = offset` and `stop = offset + length`, but having the `length` as an explicit variable is more useful).
   * These two kernels are extremely unusual in that they don't return an `Error` struct and update arguments in place for their regular outputs. 99% of the kernels have this signature so that error-handling can be done in a systematic way through an interface that doesn't support exceptions. (This is a common pattern for C and Go, languages without try-catch logic.) However, I think these two functions are special enough to join the 1% that break this pattern, along with `awkward_regularize_rangeslice` (which is an exception because it's the only function that's also called by other kernels).

Comment (trickarcher) [reply src/cpu-kernels/getitem.cpp]: Yup, thanks for the detailed explanation. I understood everything. As far as error checking goes, as far as the new commit goes, we can make provision for checking overflows in the `get` and `set` methods.

**Comment by trickarcher** [comment]
I am not sure whether this PR comment thread is the correct place to mention this, but while I was attempting to merge master into my branch, there were two merge conflicts, I resolved them. But when I tried to build the library `test30` was failing to build because of many `undefined references`. I thought it might be a merging problem but when I switched to master, the problem persisted. This is almost sure to be a linking problem, so I'll take the liberty to look into it if you don't mind.

File: src/cpu-kernels/getitem.cpp (hunk 1 above)
Comment (jpivarski) [reply src/cpu-kernels/getitem.cpp]: I haven't made any decision on overflow checking yet, so for now we don't check overflows. It's a trade-off: safety is some extreme corner cases vs speed everywhere. Usually the right thing to do is to use a numeric type that's "much bigger" than any number you're likely to encounter, and `int64_t` ought to be that, for most purposes.

If all of the bullet points in this have been addressed (I haven't checked, but I'll do another detailed scan before the merge), then you can resolve this conversation to reduce the noise in the comment thread.

Comment (trickarcher) [reply src/cpu-kernels/getitem.cpp]: Yeah, I think I have addressed the rest of the stuff.

**Comment by jpivarski** [comment]
Strangely, I see your comment about merge conflicts in my email, but not here. (I don't fully understand how GitHub comments and email mix.)

Anyway, yes, there have been two PRs since you started this PR, and you'll have to merge them in. These changes include one or two places where buffers were directly accessed because they predated this PR. You should be able to see them in the diffs.

Going forward, I'm going to be using the `IndexOf<T>::getitem` and `setitem` functions, but I can't use any new functions that this PR introduces until this PR gets merged. (I'm pretty sure the `IndexOf<T>::getitem` and `setitem` predate this PR, though...)

**Comment by trickarcher** [comment]
I am sorry,  that was a dumb mistake on my part.

I think from now on you can easily use `Index<T>::getitem` and `setitem` functions. Every other new function that I introduced just aids the separation between CPU and GPU, so you should be good to use those two functions even without my PR.

File: include/awkward/cpu-kernels/getitem.h [hunk 2]
```diff
@@ -4,6 +4,7 @@
 #define AWKWARDCPU_GETITEM_H_
 
 #include "awkward/cpu-kernels/util.h"
+#include <memory>
```
Comment (jpivarski) [inline include/awkward/cpu-kernels/getitem.h]: Now that the `std::shared_ptrs` have been removed, I don't think you need to include `memory` anymore.

File: src/cpu-kernels/getitem.cpp [hunk 3]
```diff
@@ -1096,6 +1096,38 @@ ERROR awkward_listarray64_getitem_jagged_descend_64(int64_t* tooffsets, const in
...
+void awkward_index32_setitem_at_nowrap(int32_t* ptr, int64_t offset, int64_t at, int32_t value) {
+  ptr[(size_t)(offset + at)] = value;
+}
+void awkward_indexU32_setitem_at_nowrap(uint32_t* ptr, int64_t offset, int64_t at, uint32_t value) {
+  ptr[(size_t)(offset + at)] = value;
+}
+void awkward_index64_setitem_at_nowrap(int64_t* ptr, int64_t offset, int64_t at, int64_t value) {
+  ptr[(size_t)(offset + at)] = value;
+}
```
Comment (jpivarski) [inline src/cpu-kernels/getitem.cpp:1129]: These are short enough that it's not terrible to implement them by copy-paste, though in general I write a hidden templated function and have all the public/exported specializations of it be calls into that templated function. But then again, these are so short that calling into the templated function might even be longer. The main thing is that it should be clear to a reader that they all do the same thing with different type specifications, and they do.

**Review by jpivarski — COMMENTED** [review]
Do you think you're done with this? It looks done to me; I'd just like the `#include <memory>` to be removed if it can be. (The second inline comment about copy-pasting the getitem/setitem implementations is your choice, for the reasons described there.)

When you do think you're done, give me a positive confirmation and I'll merge it. I just don't want to merge a PR when I don't know if the developer is still working on it. (It's a concurrency problem, and the "I'm done!" announcement is a lock.)

File: src/cpu-kernels/getitem.cpp (hunk 3 above)
Comment (trickarcher) [reply src/cpu-kernels/getitem.cpp:1129]: Yeah, I have actually seen a lot of these in `getitem.cpp`.

**Comment by trickarcher** [comment]
I am done with the PR. I don't know how to trigger the `CI`. It would be helpful if I could check whether all builds are passing. I have checked it locally on my Linux system and the respective C++ tests pass.

**Comment by jpivarski** [comment]
I hadn't noticed that—the CI isn't triggering. Maybe because your repository is a fork: I went into Azure to try to invoke it manually, and I could only choose from branches and commits on the main repo, not forks. If so, that's quite a deficiency of Azure. At the very least, I should be able to _manually_ run it. I'm looking into it. (I do want to run a suite of tests before merging, even though I'm pretty sure they'll all pass.)

**Comment by jpivarski** [comment]
Wait a minute: now the CI builds are visible here? Maybe I just needed to create a main repo branch; creating the duplicate PR seems to have been superfluous.

**Comment by trickarcher** [comment]
Yup, every test has passed. I guess you can merge it into master if everything's okay.
