### PR TITLE
Merge all the rpad work (#114) into new environment.

### LINKED ISSUE #73: pad
This is an operation that turns an array at some level (i.e. has an `axis` parameter) into an OptionType by putting extra `None` elements in until it reaches a given length.

Old Awkward [had an implementation of this](https://github.com/scikit-hep/awkward-array/blob/3442c51ed5dafb7d94f828c6cdc07659f9c03244/awkward/array/jagged.py#L1839-L1888), though it will probably be simpler now. Also, ignore the old `clip` parameter: that's easy enough to do with a slice after the fact. This was another proven-to-be useful operation.

Don't double-up OptionTypes: if something is already an OptionType, extend it.

The implementation might be identical for all non-OptionTypes (those are exceptional because you have to explicitly avoid doubling-up the OptionType): you just put the existing array in an `IndexedOptionArray` that points to the original array with gaps left for the new `None` values.

### PR DESCRIPTION
**Pull request by jpivarski**
@ianna I think it will be easier to merge all of your work in with side-by-side PRs. We can use Atom Teletype to collaborate on the sources in your directory, so that they get committed with your name. See you tomorrow!

### CODE REVIEW

**Comment by ianna** [comment]
Ok, the failures in the tests for negative axis are expected:
```python
>       assert awkward1.tolist(array.sizes(-1)) == [3, 3, 3, 0, 5, 2, 4, 4]
E       RuntimeError: FIXME: negative axis not implemented yet

```

**Comment by ianna** [comment]
@jpivarski - I think, I'm finished with code migration. Please, review the PR when you have time.

The `rpad` operation at `axis = 0` is either the preserves the original array type or returns an option of it.
The `rpad` operation at `axis = 1` return type is:
```python
'var * float64' == 'var * ?float64'
```

**Comment by jpivarski** [comment]
@ianna I'm reviewing it now.

File: src/libawkward/array/IndexedArray.cpp [hunk 1]
```diff
@@ -1006,6 +1006,40 @@ namespace awkward {
...
+      struct Error err = awkward_index_rpad_and_clip_axis0_64(
+        index.ptr().get(),
+        target,
+        length());
+      util::handle_error(err, classname(), identities_.get());
+      std::shared_ptr<IndexedOptionArray64> next = std::make_shared<IndexedOptionArray64>(Identities::none(), util::Parameters(), index, shallow_copy());
+      return next.get()->simplify();
+    }
+  }
+
```
Comment (jpivarski) [inline src/libawkward/array/IndexedArray.cpp]: I don't think this is right, and there are no tests. (I'm adding one.) For `ISOPTION == false`, it would be sufficient to call `project()` (no arguments) and pass down the operation to whatever that produces. For `ISOPTION == true`, `project()` drops all of the `None` values so that you can work on the non-`None` contents, then put the `Nones` back using `bytemask()`. There are examples of that in other operations.

File: src/libawkward/array/ListArray.cpp [hunk 2]
```diff
@@ -812,6 +812,110 @@ namespace awkward {
...
+      util::handle_error(err2, classname(), identities_.get());
+
+      std::shared_ptr<IndexedOptionArray64> next = std::make_shared<IndexedOptionArray64>(Identities::none(), util::Parameters(), index, content());
+      return std::make_shared<ListArray64>(Identities::none(), parameters_, starts, stops, next.get()->simplify());
+    }
+    else {
+      return std::make_shared<ListArrayOf<T>>(Identities::none(), parameters_, starts_, stops_, content_.get()->rpad_and_clip(target, axis, depth + 1));
+    }
+  }
+
```
Comment (jpivarski) [inline src/libawkward/array/ListArray.cpp]: For variable-length lists (ListArray and ListOffsetArray), `rpad` should return a new variable-length list (it does) and `rpad_and_clip` should return a regular-length list (it does not):

```python
    assert str(awkward1.typeof(listoffsetarray.rpad(5, 1))) == "var * ?float64"           # passes
    assert str(awkward1.typeof(listoffsetarray.rpad_and_clip(5, 1))) == "5 * ?float64"    # fails
```

I see that these are two implementations, but the `rpad_and_clip` needs to be reworked to (a) not generate new `starts` and `stops` because they're completely regular, and (b) return a RegularArray.

That's more straightforward for ListOffsetArray, which is guaranteed to have contiguous contents. For ListArray, you'll need a `carry`. Actually, it would be reasonable to start `ListArray::rpad_and_clip` with `toListOffsetArray64()` and let `ListOffsetArray::rpad_and_clip` do the work. That applies to `rpad_and_clip` (because it has to return a RegularArray, which has contiguous contents, and therefore contents need to be carried) and not `rpad` (because it's going to return a ListArray, anyway).

**Review by jpivarski — COMMENTED** [review]
Very nearly there! Most of the cases you've tested are correct, the exception being the type of `rpad_and_clip` (should be regular, not jagged; otherwise, users could perform the clip with a slice and we wouldn't need two operations).

As we saw when we were looking at this on Skype, the `axis == 0` case is so different from the rest that perhaps it should be pulled out to avoid cluttering the other operations. For instance, as you enter any `rpad` or `rpad_and_clip`, the first thing you do is

```c++
if (axis == 0) {
  return rpad_axis0(target, false);
}
```

where

```c++
const std::shared_ptr<Content> rpad_axis0(int64_t target, bool clip) {
  ...
}
```

wraps whatever this array is in an IndexedOptionArray64 with enough `None` values at the end to reach the `target`, clipping or not clipping based on `bool clip`. Afterward, call `simplify()` on the IndexedOptionArray64 and it will do the right thing, regardless of whether its content is indexed.

I've also added some tests for IndexedArrays, RecordArrays, and UnionArrays that demonstrate what rpad is supposed to do in each case. In their implementations, you can use the fact that you know that `axis > 0` rpad/rpad-and-clip does not change the length of what it's applied to or the meaning of each element (and hence, the `index` of a UnionArray is still valid).

File: src/libawkward/array/ListArray.cpp (hunk 2 above)
Comment (ianna) [reply src/libawkward/array/ListArray.cpp]: @jpivarski - thanks! Shall I make a bugfix PR?

Comment (jpivarski) [reply src/libawkward/array/ListArray.cpp]: You could either update this PR or merge this and start a bugfix PR. In the latter case, be sure to remove the failing tests I added so that master doesn't break, then re-introduce them into your bugfix PR(s). Those failing tests are supposed to be informative, but master is not allowed to break.

If you do want to do this through a bugfix PR, let me know when you've removed the failing tests and all tests pass so that I can merge and deploy (because I like to be in the habit of deploying every change to master).

Comment (ianna) [reply src/libawkward/array/ListArray.cpp]: I'll do it in this PR - I thought you've already merged it, but it was a message about something else :-)

Comment (ianna) [reply src/libawkward/array/ListArray.cpp]: done

File: src/libawkward/array/IndexedArray.cpp (hunk 1 above)
Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp]: * `rpad_axis0` is done.
  * `ISOPTION == false` is done. I've started working on `ISOPTION == true`.

I'll cleanup operations afterwards.

Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp]: done

**Comment by ianna** [comment]
@jpivarski - I think, all your comments are addressed.

**Comment by jpivarski** [comment]
I agree that it's done. I just added a high-level interface and interacted with it on the command line. It behaved in a natural way, except for one detail:

```python
>>> array = ak.Array([1, 2, 3, 4, 5])
>>> ak.rpad(array, 7, axis=0)
<Array [1, 2, 3, 4, 5, None, None] type='7 * ?int64'>
>>> ak.rpad(array, 3, axis=0)
<Array [1, 2, 3, 4, 5] type='5 * int64'>
>>> ak.rpad(array, 3, axis=0, clip=True)
<Array [1, 2, 3] type='3 * ?int64'>
```

If the `axis` is `0` and the target length is less than the actual length of the array, the type is not an option type (`int64` above, rather than `?int64`). For consistency—to avoid surprises in scripts—I'm going to want to make that an option type as well. `axis > 0` does not have this issue:

```python
>>> array = ak.Array([[1, 2], [3], [4, 5]])
>>> ak.rpad(array, 2)
<Array [[1, 2], [3, None], [4, 5]] type='3 * var * ?int64'>
>>> ak.rpad(array, 1)
<Array [[1, 2], [3], [4, 5]] type='3 * var * ?int64'>
>>> ak.rpad(array, 1, clip=True)
<Array [[1], [3], [4]] type='3 * 1 * ?int64'>
```

because we can't know the lengths of inner lists before deciding what the structure of the output is going to look like.

However, we should leave this unfixed for now (maybe make an issue). The "UnmaskedArray" class would be ideally suited to solve this: instead of returning a `shallow_copy` from `Content::rpad_axis0`, we would return

```c++
std::make_shared<UnmaskedArray>(Identities::none(), util::Parameters(), shallow_copy());
```

where UnmaskedArray gives something option type, but none of the values are actually `None`. It's a formality we can deal with later.

But other than that formality, this is great; I think we should merge it! Give me an indication that you're really done (that you don't have any local changes left to submit) and I'll merge it.

Thanks a lot!

**Comment by ianna** [comment]
Thanks, @jpivarski! Yes, please, merge it.

**Comment by jpivarski** [comment]
I'll do that. Do you want to call on Skype and talk about what's next?

**Comment by ianna** [comment]
> I'll do that. Do you want to call on Skype and talk about what's next?

Yes, please :-)

**Comment by jpivarski** [comment]
I'm online now.
