### PR TITLE
fix: (v1) merging options should produce an option

### LINKED ISSUE #2579: `-1` in `IndexedArrays` of Awkward v1 (needs a bug-fix release)
### Version of Awkward Array

1.10.3

### Description and code to reproduce

From Andrew Roberts on Mattermost/LPCPhysDiscuss/Coffea:

it goes invalid after the `ak.where`. All of the arrays that are inputted to the function are valid. here they are in my analysis script (hope the message isn't too long):

a content `[[], [], []]`
a layout
```
<ListOffsetArray64>
    <offsets><Index64 i="[0 0 0 0]" offset="0" length="4" at="0x0000081d54a0"/></offsets>
    <content><EmptyArray/></content>
</ListOffsetArray64>
```
a is_valid `True`
b content `[[None, None, None], [None, None], [None, None, None]]`
b layout
```
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 5 8]" offset="0" length="4" at="0x0000081d8280"/></offsets>
    <content><IndexedOptionArray64>
        <index><Index64 i="[-1 -1 -1 -1 -1 -1 -1 -1]" offset="0" length="8" at="0x000008413640"/></index>
        <content><NumpyArray format="?" shape="0" data="" at="0x000008342eb0"/></content>
    </IndexedOptionArray64></content>
</ListOffsetArray64>
```
b is_valid `True`
c content `[[126, 59.3, 37.9], [54.5, 46.2], [126, 73.5, 32.3]]`
c layout
```
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 5 8]" offset="0" length="4" at="0x0000091e96d0"/></offsets>
    <content><IndexedArray64>
        <index><Index64 i="[5241 5242 5243 55080 55081 85773 85774 85775]" offset="0" length="8" at="0x000009082f70"/></index>
        <content><NumpyArray format="f" shape="90906" data="54.8438 50.4688 20.7812 17.8594 71.375 ... 53.9062 45.125 28.2188 22.6562 17.6094" at="0x00000927dc50">
            <parameters>
                <param key="__doc__">"pt"</param>
            </parameters>
        </NumpyArray></content>
    </IndexedArray64></content>
</ListOffsetArray64>
```
c is_valid `True`
d content `[[False, False, False], [False, False], [False, False, False]]`
d layout
```
<ListArray64>
    <starts><Index64 i="[8 11 13]" offset="0" length="3" at="0x00000901c3d0"/></starts>
    <stops><Index64 i="[11 13 16]" offset="0" length="3" at="0x0000084281e0"/></stops>
    <content><IndexedArray64>
        <index><Index64 i="[-1 -1 -1 -1 -1 -1 -1 -1 5241 5242 5243 55080 55081 85773 85774 85775]" offset="0" length="16" at="0x0000083ca9f0"/></index>
        <content><NumpyArray format="?" shape="90906" data="false false false false false ... false false false false false" at="0x0000094b1790"/></content>
    </IndexedArray64></content>
</ListArray64>
```
d is_valid `False`

thanks for the help!

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #2579, depends upon #2583

### CODE REVIEW

File: src/libawkward/array/IndexedArray.cpp [hunk 1]
```diff
@@ -1870,7 +1870,6 @@ namespace awkward {
       }
 
       if (IndexedArray32* raw = dynamic_cast<IndexedArray32*>(array.get())) {
-        is_option = false;
```
Comment (agoose77) [inline src/libawkward/array/IndexedArray.cpp:1873]: This is false by default. We want this flag to be sticky; if any content is an option, the result should also be an option.

Comment (jpivarski) [reply src/libawkward/array/IndexedArray.cpp:1873]: That's right—it's initialized to `false` on line 1854 and each of the `IndexedOptionArray*` cases turns it to `true` around lines 1918 and 1933. And I understand the logic: if _any_ index-like node is an `IndexedOptionArray*`, the result must be. Without this fix, the option-ness of the output depended on the _last_ of the inputs.

I think this is ready to go!

**Review by jpivarski — APPROVED** [review]
See below!
