### PR TITLE
fix: string array numpy conversion fails with int32 offsets from parquet

### LINKED ISSUE #3696: Parquet string serialization breaks conversion to numpy
### Version of Awkward Array

2.8.9

### Description and code to reproduce

```python
a = ak.Array([{"foo": "bar"}, {"foo": "baz"}])
b = np.asarray(a["foo"])

ak.to_parquet(a, "test.parquet")
x = ak.from_parquet("test.parquet")
y = np.asarray(x["foo"])  # !!!
```

Results in

```
  File "/Users/dcm/Developer/awkward/bugex.py", line 15, in main
    y = np.asarray(x["foo"])
  File "/Users/dcm/Developer/awkward/src/awkward/highlevel.py", line 1548, in __array__
    with ak._errors.OperationErrorContext(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        "numpy.asarray", (self,), {"dtype": dtype, "copy": copy}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ):
    ^
  File "/Users/dcm/Developer/awkward/src/awkward/_errors.py", line 80, in __exit__
    raise self.decorate_exception(exception_type, exception_value)
  File "/Users/dcm/Developer/awkward/src/awkward/highlevel.py", line 1553, in __array__
    return convert_to_array(self._layout, dtype=dtype, copy=copy)
  File "/Users/dcm/Developer/awkward/src/awkward/_connect/numpy.py", line 511, in convert_to_array
    out = ak.operations.to_numpy(layout, allow_missing=False)
  File "/Users/dcm/Developer/awkward/src/awkward/_dispatch.py", line 67, in dispatch
    next(gen_or_result)
    ~~~~^^^^^^^^^^^^^^^
  File "/Users/dcm/Developer/awkward/src/awkward/operations/ak_to_numpy.py", line 48, in to_numpy
    return _impl(array, allow_missing)
  File "/Users/dcm/Developer/awkward/src/awkward/operations/ak_to_numpy.py", line 60, in _impl
    return numpy_layout.to_backend_array(allow_missing=allow_missing)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcm/Developer/awkward/src/awkward/contents/content.py", line 1126, in to_backend_array
    return self._to_backend_array(allow_missing, backend)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcm/Developer/awkward/src/awkward/contents/listoffsetarray.py", line 2064, in _to_backend_array
    backend[
    ~~~~~~~^
        "awkward_NumpyArray_prepare_utf8_to_utf32_padded",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        _max_code_points.dtype.type,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ](
    ^
  File "/Users/dcm/Developer/awkward/src/awkward/_backends/numpy.py", line 32, in __getitem__
    return NumpyKernel(awkward_cpp.cpu_kernels.kernel[index], index)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: ('awkward_NumpyArray_prepare_utf8_to_utf32_padded', <class 'numpy.uint8'>, <class 'numpy.int32'>, <class 'numpy.int64'>)

This error occurred while calling

    numpy.asarray(
        <Array ['bar', 'baz'] type='2 * string'>
        dtype = None
        copy = None
    )
```

I think we just need to add kernel specializations for `int32`/`uint32` -- should have a PR shortly.

### PR DESCRIPTION
**Pull request by DylanModesitt**
Closes: #3696

Fixes a bug where converting string arrays to numpy fails after deserializing from parquet with `string_to32=True` (the default). Upon deserialization, the resulting `ListOffsetArray` has int32 offsets instead of int64 & the utf8 string conversion kernels only had int64 offset specializations.

Added int32 and uint32 kernel specializations for the three UTF8/padding kernels:

- `awkward_NumpyArray_prepare_utf8_to_utf32_padded`
- `awkward_NumpyArray_utf8_to_utf32_padded`
- `awkward_NumpyArray_pad_zero_to_length`

### CODE REVIEW

**Comment by DylanModesitt** [comment]
Think the GPU Test failures are unrelated? Seems like a CMake/compiler configuration issues in the action.

**Comment by ianna** [comment]
> Think the GPU Test failures are unrelated? Seems like a CMake/compiler configuration issues in the action.

I think so too. The CUDA kernels have been implemented correctly already. I'll have a look. Thanks!

File: awkward-cpp/src/cpu-kernels/awkward_NumpyArray_pad_zero_to_length.cpp [hunk 1]
```diff
@@ -30,13 +30,41 @@ ERROR awkward_NumpyArray_pad_zero_to_length(
...
+  uint8_t* toptr) {
+  return awkward_NumpyArray_pad_zero_to_length<uint8_t, int32_t>(
+    fromptr,
+    fromoffsets,
+    offsetslength,
+    target,
+    toptr);
+}
+
+ERROR awkward_NumpyArray_pad_zero_to_length_uint8_uint32(
```
Comment (ariostas) [inline awkward-cpp/src/cpu-kernels/awkward_NumpyArray_pad_zero_to_length.cpp:47]: Is it worth adding uint64 as well?

Comment (ariostas) [reply awkward-cpp/src/cpu-kernels/awkward_NumpyArray_pad_zero_to_length.cpp:47]: Nevermind, I don't think it's worth it.

File: tests/test_3697_parquet_string_int32_offsets.py [hunk 2]
```diff
@@ -0,0 +1,166 @@
...
+
+    # This should work now with int32 offset kernel specializations
+    y = np.asarray(x["foo"])
+    assert y.dtype.kind == "U"
+    assert list(y) == ["bar", "baz"]
+
+    # Clean up
+    import os
+
+    os.remove("test_string_to32.parquet")
```
Comment (ariostas) [inline tests/test_3697_parquet_string_int32_offsets.py]: You should use the `tmp_path` fixture instead. You can find an example here.

https://github.com/scikit-hep/awkward/blob/36824fdf871349a16d3da6e54150048dce232d08/tests/test_2646_from_parquet_highlevel.py#L12-L22

**Comment by ariostas** [comment]
The failure on macos-14 was due to a stale cache, so I cleared the cache and re-run it. The GPU failure is pretty confusing because other PRs work fine. I'll look into it some more.

**Comment by ariostas** [comment]
Oh it seems like it's also a cache issue. In other PRs it's using a cached wheel, but in this one it's not. I'll fix it.

File: tests/test_3697_parquet_string_int32_offsets.py (hunk 2 above)
Comment (DylanModesitt) [reply tests/test_3697_parquet_string_int32_offsets.py]: Ty, will do

**Review by ariostas — APPROVED** [review]

**Review by ianna — APPROVED** [review]
@DylanModesitt - Great! Thanks for fixing it. The tests pass, I'll enable auto-merge. Thanks.
