### PR TITLE
intermittent error bugfix

### LINKED ISSUE #320: The MacOS test has an intermittent error in ak.argsort
It is usually cured by rerunning it, but an intermittent error is an error: something's wrong. The error manifests itself as a `ValueError` evaluating (I think!) one of the reducer tests. Next time, I should paste the error output here.

### PR DESCRIPTION
**Pull request by ianna**
Addressing issue #320

### CODE REVIEW

**Comment by ianna** [comment]
The `42adfe5` build fail with:
```log
error C3861: 'assert': identifier not found
```
that is fixed in the next commit.

**Comment by ianna** [comment]
@jpivarski - Unfortunately, I could not reproduce the error, not even once. So, trying to guess from the previous reports.
 
a) it is cured by re-running and b) the error message shows a non zero `offset` in an `IndexedArray` that is most likely the case of the error

The changes in this PR make sure that the `offset` is always initialised. The constructors are explicit, the explicit copy constructors are used between C++ and Python (by pybind11). Well, it could be an overkill and I should trust the compiler to do implicit copies correctly...

Please, have a look when you have time. Thanks!

File: include/awkward/Index.h [hunk 1]
```diff
@@ -220,7 +222,7 @@ namespace awkward {
     /// @brief See #ptr_lib
     const kernel::lib ptr_lib_;
     /// @brief See #offset.
-    const int64_t offset_;
+    const int64_t offset_ = 0;
```
Comment (jpivarski) [inline include/awkward/Index.h]: Is this supposed to be related to the bug? If there's any way for `offset_` to be uninitialized in an `IndexOf<T>` instance, then that itself is a bug that needs to be addressed at its source (assuming `0` is a bad idea: it must always be given when the instance is constructed).

File: include/awkward/array/RawArray.h [hunk 2]
```diff
@@ -1292,9 +1292,9 @@ namespace awkward {
   private:
     const kernel::lib ptr_lib_;
     const std::shared_ptr<T> ptr_;
-    const int64_t offset_;
-    const int64_t length_;
-    const int64_t itemsize_;
+    const int64_t offset_ = 0;
+    const int64_t length_ = 0;
+    const int64_t itemsize_ = 0;
```
Comment (jpivarski) [inline include/awkward/array/RawArray.h]: Same question as above on `IndexOf<T>`: if there's any way for `offset_`, `length_`, or `itemsize_` to be uninitialized in a `RawArrayOf<T>` instance, then that itself is a bug. We don't want to hide it by giving these fields default values.

File: include/awkward/array/RecordArray.h [hunk 3]
```diff
@@ -441,7 +447,7 @@ namespace awkward {
     /// @brief See #recordlookup.
     const util::RecordLookupPtr recordlookup_;
     /// @brief See #length.
-    int64_t length_;
+    int64_t length_ = 0;
```
Comment (jpivarski) [inline include/awkward/array/RecordArray.h]: Same as above: `length_` needs to always be set by a constructor, never assumed to be `0` if that somehow gets missed.

File: include/awkward/array/RegularArray.h [hunk 4]
```diff
@@ -81,7 +87,7 @@ namespace awkward {
 
   private:
     const FormPtr content_;
-    int64_t size_;
+    int64_t size_ = 0;
```
Comment (jpivarski) [inline include/awkward/array/RegularArray.h]: Same comment as above.

File: include/awkward/array/RegularArray.h [hunk 5]
```diff
@@ -366,7 +372,7 @@ namespace awkward {
 
   private:
     const ContentPtr content_;
-    int64_t size_;
+    int64_t size_ = 0;
```
Comment (jpivarski) [inline include/awkward/array/RegularArray.h]: Same comment as above.

File: src/libawkward/Index.cpp [hunk 6]
```diff
@@ -84,7 +84,6 @@ namespace awkward {
   IndexOf<T>::IndexOf(int64_t length, kernel::lib ptr_lib)
     : ptr_(kernel::malloc<T>(ptr_lib, length * (int64_t)sizeof(T)))
     , ptr_lib_(ptr_lib)
-    , offset_(0)
```
Comment (jpivarski) [inline src/libawkward/Index.cpp]: Why was this removed? This particular constructor should set `offset_` to `0` (because we're initializing the array right here; we know it has an offset of `0`). The others should set it to a given value.

**Review by jpivarski — COMMENTED** [review]
The errors were quite rare—they only happened three or four times since the first report on July 6 (#320), which means hundreds of CI runs. Perhaps they could be induced on a Mac by re-running that test in a tight loop, but then again, maybe that sets up the memory in such a way that new allocations hit a lucky spot of memory 100% of the time.

I created a branch (not a PR!) to try to make the bug more likely:

https://github.com/scikit-hep/awkward-1.0/compare/master...jpivarski/intermittent_error_bugfix-DEBUG

It is relative to master, so the bug should still be there. (I didn't want to take the chance that your PR fixed it, because then we'd be chasing nothing!) This assigns `-999` to all elements of all Indexes and integers that are to be filled before filling them in `argsort_next` with the idea that some value might be left unfilled and we're looking at uninitialized memory. That's probably not it because doing so didn't cause an error on Linux, and a value of `-999` ought to cause some problems. (I also tried switching them to positive `999`, in case it's something that's just compared with zero, like in IndexedOptionArray. That didn't trigger it either, on Linux.)

If you check out this branch and run it on MacOS, does it make the bug show itself? (What about changing all the `-999` to `999`? Adding more or bigger `little_arrays` in `test_IndexedOffsetArray`? In Python 2 vs 3?) If none of that brings out the bug, then perhaps we should just apply your possible fix and keep an eye on it for the next few months.

---------------------------------------

There are a lot of changes here unrelated to the bug; they're C++ features from clang-tidy. Some of them explicitly define or delete special functions (copy/assignment constructors, etc.), some of them add `explicit` and `final` keywords, which I'm not familiar with, though I've just read up on them. (I'm not sure why we're setting `final` on Forms; the class hierarchies are very flat, most concrete classes directly inherit from a single abstract class. Unintended subclassing is not something we're likely to do.) From the documentation, these seem to be exclusively C++11 features, which is required, though I don't know if CI would catch a C++14 feature, if one were accidentally used.

I've written inline comments about initializing class members to `0`. I don't know if that's related to the clang-tidy or if that was intended to fix the bug. Either way, I'd rather not do that because it gives the impression that constructors don't have to assign them explicitly. Everything here should be 100% RAII, with all class members set by every constructor. If there's a way to enforce it with a C++11 feature, I'd be up for that.

**Comment by ianna** [comment]
@jpivarski - Thanks! Using your branch I managed to reproduce and fix the bug.

Last thing to do: a newly introduced parameter in https://github.com/scikit-hep/awkward-1.0/pull/435/commits/0619e197cf10b7912ac9d740f349ff9f576b4e81 needs to be documented to fix the error:
```shell
Starting: Generate Kernel specification
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.164.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
python dev/generate-kernelspec.py
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/9db7d3b6-b487-4f50-97f2-37657c0ebe8f.sh
Traceback (most recent call last):
  File "dev/generate-kernelspec.py", line 855, in <module>
    paramchecks = get_paramcheck(funcroles, tokens, funcargs)
  File "dev/generate-kernelspec.py", line 821, in get_paramcheck
    funcs[funcname][arg] = funcroles[keyfunc][arg]["check"]
KeyError: Token(PARAMNAME, 'nextparentslength')

##[error]Bash exited with code '1'.
Finishing: Generate Kernel specification
```

**Comment by jpivarski** [comment]
> @jpivarski - Thanks! Using your branch I managed to reproduce and fix the bug.

Great! I'm glad that helped.

> Last thing to do: a newly introduced parameter in [0619e19](https://github.com/scikit-hep/awkward-1.0/commit/0619e197cf10b7912ac9d740f349ff9f576b4e81) needs to be documented to fix the error:

I think you did the right thing in 3d6ee018d120fd69ca9dde41d4c276b10009a23f, namely adding `@param` in the header file for the new parameter, but I'll ping @reikdas in case the generated kernels fail again. So far, they're looking good.

Note to self: I should add these extra steps to the `localbuild.py` script so that it's easier to do them locally. I usually

```bash
cat .ci/azure-buildtest-awkward.yml
```

and find the command lines to copy-paste to test them locally, but this is not sustainable.

--------------------

@ianna If the assignment of class members to zero is no longer necessary, I'd like to remove those changes. If there's a way to make the compiler raise a warning or an error for any constructor that doesn't set all of the class members explicitly, then let's turn on that compiler check instead. As I said in my review comments above, leaving these members uninitialized is bad, but arbitrarily setting them to zero is almost as bad.

If you think our diligence in manually checking that all constructors set all class members is not good enough and there's no automated way to check for it, then I suppose the next best thing would be to make the default values `-999` to try to ensure a runtime error. The problem with that is that the runtime error would likely be a segfault, and segfaults are hard to debug.

**Comment by ianna** [comment]
@jpivarski - hopefully it fixes the bug without introducing unrelated changes :-)

Perhaps, it would be useful if the script `dev/generate-kernelspec.py` produces an error such as:

"Failed to generate documentation for parameter` 'nextparentslength'.` Have you forgotten to document it in the file `'include/awkward/kernels/sorting.h'`?"

I think, there is enough information in the script to print these details.

File: src/libawkward/array/IndexedArray.cpp [hunk 7]
```diff
@@ -2215,14 +2226,15 @@ namespace awkward {
                                               stable,
                                               keepdims);
 
-    Index64 nextoutindex(index_.length());
+    Index64 nextoutindex(parents_length);
```
Comment (jpivarski) [inline src/libawkward/array/IndexedArray.cpp:2229]: I take it this was the significant change, right?

File: src/cpu-kernels/sorting.cpp [hunk 8]
```diff
@@ -575,14 +575,14 @@ ERROR awkward_IndexedArray_local_preparenext_64(
...
+    const int64_t parentslength,
+    const int64_t* nextparents,
+    const int64_t nextlen) {
   int64_t j = 0;
   for (int64_t i = 0;  i < parentslength;  i++) {
     int64_t parent = parents[i];
     int64_t start = starts[parent];
-    int64_t nextparent = nextparents[j];
-    if (parent == nextparent) {
+    if (j < nextlen  &&  parent == nextparents[j]) {
```
Comment (jpivarski) [inline src/cpu-kernels/sorting.cpp:585]: Oh, and this must be significant, too, right?

**Review by jpivarski — APPROVED** [review]
Great! When the tests pass one last time, I'll merge it.

As I understand it (two comments below), the significant changes were

1. adding a `nextlen` parameter to the kernel
2. initializing `nextoutindex` with `parents_length`, rather than `index_length`.

Other than that, there was a lot of tidying and fixing of warnings. In one, a warning was fixed by casting an integer type, but I changed it from `unsigned int` to `rj::SizeType` because that's the specific type named by the RapidJSON API. At the same time, I went through and made sure we always cast to specific integer type sizes because that's a major source of bugs on Windows (which supports both 32-bit and 64-bit). That's the reason for the last CI run.

Thanks!!!

File: src/libawkward/array/IndexedArray.cpp (hunk 7 above)
Comment (ianna) [reply src/libawkward/array/IndexedArray.cpp:2229]: it looks like the length of parents and index are equal in all tested cases, but I changed it to be more explicit because the iteration is on parents

File: src/cpu-kernels/sorting.cpp (hunk 8 above)
Comment (ianna) [reply src/cpu-kernels/sorting.cpp:585]: That was it! Sometimes it could happen that `nextparent` at `nextlen` is equal to `parent`. For example, the changes in the `argsort` function from your branch triggered this problem in the `sort` function in a last test:
```
parents:
0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 
next parents:
0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 0, 3, 5, 6, 1, 
starts:
0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10, 
tocarry:
0, 1, 2, 3, -1, 4, 5, -1, -1, -1, 6, 7, 8, 9, -1, 
```
